### ISSUE TITLE
Question about contribution

### ISSUE THREAD

**Issue by buginux** [matthewpalmer/Charter#12]
I'm sorry but I have a question if I want to contribute to this repository, which branch do I need to track or modify.

I've tried the develop branch, but the app crashed when I click any of the Mailing Lists item, the cause seems to be the realm, do I need to run the backend myself or do I need to do some additional configuration?

I am interested in this repository, and I want to contribute. It will be great if you can give me some additional information. Thanks.

**Comment by matthewpalmer** [comment]
Awesome, thanks for being keen to contribute!

The develop branch is normally the right one to branch off, however develop is super broken at the moment because I'm in the midst of a big migration from an iOS app-only thing to an iOS app + backend thing.

So right now it's probably okay to branch off master. It won't be a clean merge into develop when we get to that but I'm happy to bring the changes across manually when develop's in a better state.

What were you thinking of contributing? Just want to make sure you don't waste your time with something that might be affected by the server migration stuff.

(This reminds me that I should totally add a contributors file/section to the readme :smile: )

Thanks again, and let me know if you have any other questions :+1: 

Matt

**Comment by matthewpalmer** [comment]
Hey

I've just merged develop into master, so everything should stabilise a bit going forward. I'll delete the develop branch soon, and make master the primary development branch.

Closing this, but feel free to reopen if there's anything else :+1: 

Matt
